### ISSUE TITLE
For Inspur's server ipmitool is used normally, but it prompts the username invalid error, and the corresponding solution.

### ISSUE THREAD

**Issue by yanghesong** [prometheus-community/ipmi_exporter#123]
Both BMC User 1 and User 2 cannot be used, and a new user is required to work properly.

**Comment by yahaa** [comment]
I got the same problem, but I solved it using the following config:

```yaml
modules:
  default:
    user: "admin"
    pass: "xxx" # replace it to your actualy admin password
    privilege: "ADMIN" # privilege level can sees in man ipmi-sensors
   driver: LAN_2_0 
```

You can also using the  following command line to check it:

```bash
/usr/sbin/ipmi-sensors -h xxx -u amdin -p xxx --privilege-level=ADMIN -D LAN_2_0
```
