### ISSUE TITLE
Failed to collect metrics from the remote ipmi server

### ISSUE THREAD

**Issue by 2018-11-27** [prometheus-community/ipmi_exporter#138]
My `ipmi_remote.yml` configuration file is as follows:
```yaml
modules:
  default:
    user: "zhuyk4"
    pass: "user@zhuyk4"
    driver: "LAN_2_0"
    privilege: "user"
    timeout: 10000
    collectors:
      - bmc
      - ipmi
      - chassis
    exclude_sensor_ids:
      - 2
      - 29
      - 32
      - 50
      - 52
      - 55
```
I launch it like this:
```shell
[root@zhuyk4 ipmi_exporter]# ./ipmi_exporter --config.file=ipmi_remote.yml
INFO[0000] Starting ipmi_exporter                        source="main.go:83"
INFO[0000] Loaded config file ipmi_remote.yml            source="config.go:115"
INFO[0000] Listening on :9290                            source="main.go:147"
```
**When I access it in my browser (`http://10.121.118.101:9290/ipmi?target=10.121.114.5`), I get:**
```
# HELP oi_ipmi_up '1' if a scrape of the IPMI device was successful, '0' otherwise.
# TYPE oi_ipmi_up gauge
oi_ipmi_up{collector="bmc"} 0
oi_ipmi_up{collector="chassis"} 0
oi_ipmi_up{collector="ipmi"} 0
```
**Program log output:**
```
INFO[0002] Can not find info contain 'IPMI Device Information' from dmidecode --type 38  source="collector.go:539"
```
I don't know what I did wrong. I want to get remote ipmi server metrics.
