### ISSUE TITLE
collector_cmd seems to force /usr/sbin prefix

### ISSUE THREAD

**Issue by growly** [prometheus-community/ipmi_exporter#199]
Not sure why this is happening, whether it's to do with how the user is set up (PATH) or whether it's part of this codebase, but in trying to force `sudo` collection on Debian 12.0 it seems as if ipmi_exporter tries to force `/usr/sbin/` as a prefix for the command.

Here's my ipmi_local.yml:

```yaml
modules:
        default:
                # Available collectors are bmc, ipmi, chassis, dcmi, sel, and sm-lan-mode
                collectors:
                - bmc
                - ipmi
                - dcmi
                - chassis
                - sel
                # Got any sensors you don't care about? Add them here.
                exclude_sensor_ids:
                - 2
                - 29
                - 32
                collector_cmd:
                  bmc: sudo
                  ipmi: sudo
                  dcmi: sudo
                  chassis: sudo
                  sel: sudo
                custom_args:
                  bmc:
                  - "/usr/sbin/bmc-info"
                  ipmi:
                  - "/usr/sbin/ipmimonitoring"
                  sel:
                  - "/usr/sbin/ipmi-sel"
                  dcmi:
                  - "/usr/sbin/ipmi-dcmi"
                  chassis:
                  - "/usr/sbin/ipmi-chassis"
                  sel:
                  - "/usr/sbin/ipmi-sel"
```

With this I get the following error deep in syslog:
```Failed to collect SEL data" target=[local] error="error running /usr/sbin/sudo: fork/exec /usr/sbin/sudo: no such file or directory:```

Fair enough, my sudo lives in /usr/bin and there's no link from /usr/sbin.

So I tried making it an absolute path:

```yaml
                collector_cmd:
                  ipmi: /usr/bin/sudo
```

But then I get this!

```
Failed to collect sensor data" target=[local] error="error running /usr/sbin/usr/bin/sudo: fork/exec /usr/sbin/usr/bin/sudo: no such file or directory: 
```

The fix is to add a symlink from /usr/sbin/sudo to /usr/bin/sudo, but that's not gonna work out of the box. Seems like this is surprising behaviour for specifying a an absolute command.

Don't have a moment to find the culprit in the codebase so sorry I can't do more of my own homework. Thought I'd report the issue anyway.

**Comment by bitfehler** [comment]
This is caused by a patch that Debian applies, see #153 for all the details if you care :slightly_smiling_face: 

I think the workaround would currently be to start the exporter with `--freeipmi.path=/usr/bin` and use just `sudo` in the config file. The fact that the prefix gets added to an absolute path seems a bit silly indeed, I'll take a look at that.

**Comment by bitfehler** [comment]
In the next release, your totally correct approach of setting the `collector_cmd` to `/usr/bin/sudo` should also work.

**Comment by growly** [comment]
tysm 🙏

**Comment by maheshglm** [comment]
Hi, It is happening with Centos as well, I see the issue is fixed but new **version** is not yet released, so I tried to build from latest code base and testing. But I still some issue with exporter. 

this is my configuration

```
ExecStart=/usr/local/bin/ipmi_exporter \
--config.file=/etc/ipmi_exporter.yaml \
--freeipmi.path=/usr/local/bin \
--log.level=debug
``` 

**Config file:**

```
    collector_cmd:
      ipmi: /bin/sudo
      sel: /bin/sudo
      bmc: /bin/sudo
    custom_args:
      ipmi:
        - "/usr/local/bin/ipmimonitoring"
      sel:
        - "/usr/local/bin/ipmi-sel"
      bmc:
        - "/usr/local/bin/bmc-info"
```

**Error:**

```
Jul 19 16:46:05 XXXX ipmi_exporter[25892]: ts=2024-07-19T08:46:05.369Z caller=freeipmi.go:167 level=debug msg=Executing command=/bin/sudo args="[/usr/local/bin/ipmi-sel --info --config-file /tmp/ipmi_exporter-38db14a0e79b7913ec06326bfa69972c]"
```
