### ISSUE TITLE
No metrics "ipmi_dcmi_power_consumption_watts"  in  aarch64

### ISSUE THREAD

**Issue by gitzhou-sin** [prometheus-community/ipmi_exporter#215]
My configuration file:
```
modules:
  default:
    # Available collectors are bmc, bmc-watchdog, ipmi, chassis, dcmi, sel, sel-events and sm-lan-mode
    collectors:
      - bmc
      - ipmi
      - dcmi
      - chassis
      - sel
    # Got any sensors you don't care about? Add them here.
    exclude_sensor_ids:
      - 2
      - 29
      - 32
    # Define custom metrics for SEL entries
    sel_events:
      - name: correctable_memory_error
        regex: Correctable memory error.*
```

My OS:
```
cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (AltArch)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (AltArch)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
```

metrics  info
![image](https://github.com/user-attachments/assets/df071ba7-6079-42f7-bd6c-865b50a25525)
