### ISSUE TITLE
sm-lan-mode doesn't work

### ISSUE THREAD

**Issue by yuzhichang** [prometheus-community/ipmi_exporter#94]
exporter config:
```
modules:
  default:
    user: root
    pass: calvin
    driver: "LAN_2_0"
    privilege: "admin"
    timeout: 10000
    # collectors: [bmc, ipmi, dcmi, sel, chassis, sm-lan-mode]
    collectors: [sm-lan-mode]
    exclude_sensor_ids: []
```

I got error:
```
level=debug ts=2021-12-18T07:03:14.189Z caller=freeipmi.go:143 msg=Executing command=ipmi-raw args="[0x0 0x30 0x70 0x0c 0 --config-file /tmp/ipmi_exporter-427c4cb2556d3eaaeb284a5498daf106 -h 192.168.102.98]"
level=error ts=2021-12-18T07:03:14.241Z caller=collector_sm_lan_mode.go:60 msg="Unexpected number of octets" target=192.168.102.98 octets="unsupported value type"
level=debug ts=2021-12-18T07:03:14.242Z caller=collector.go:84 msg="Scrape duration" target=192.168.102.98 duration=0.052460672

```

The `ipmi-raw` command returns only 2 bytes:
```
[root@vm101106 ~]# /usr/sbin/ipmi-raw --driver-type=LAN_2_0 --hostname=192.168.102.98 --username=root --password=calvin 0x0 0x30 0x70 0x0c 0
192.168.102.98: rcvd: 70 C1 
```
